#ifndef BLDC_AXI_CONTROLLER_REGS_H
#define BLDC_AXI_CONTROLLER_REGS_H

#include <stdint.h>

#define BLDC_AXI_CONTROLLER_ID_VALUE                UINT32_C(0x424C4443)

#define BLDC_AXI_CONTROLLER_REG_ID                  UINT32_C(0x00)
#define BLDC_AXI_CONTROLLER_REG_CONTROL             UINT32_C(0x04)
#define BLDC_AXI_CONTROLLER_REG_PWM_CFG             UINT32_C(0x08)
#define BLDC_AXI_CONTROLLER_REG_DEADTIME            UINT32_C(0x0C)
#define BLDC_AXI_CONTROLLER_REG_COMM_CFG            UINT32_C(0x10)
#define BLDC_AXI_CONTROLLER_REG_IRQ_MASK            UINT32_C(0x14)
#define BLDC_AXI_CONTROLLER_REG_IRQ_STATUS          UINT32_C(0x18)
#define BLDC_AXI_CONTROLLER_REG_MAIN_WINDOW         UINT32_C(0x1C)
#define BLDC_AXI_CONTROLLER_REG_FIFO_DATA           UINT32_C(0x20)
#define BLDC_AXI_CONTROLLER_REG_FIFO_STATUS         UINT32_C(0x24)
#define BLDC_AXI_CONTROLLER_REG_SPEED_TARGET        UINT32_C(0x28)
#define BLDC_AXI_CONTROLLER_REG_SPEED_WINDOW        UINT32_C(0x2C)
#define BLDC_AXI_CONTROLLER_REG_SPEED_STATUS        UINT32_C(0x30)
#define BLDC_AXI_CONTROLLER_REG_STATUS              UINT32_C(0x34)
#define BLDC_AXI_CONTROLLER_REG_BRAKE_CFG           UINT32_C(0x38)

#define BLDC_AXI_CONTROLLER_PWM_PERIOD_MIN          UINT32_C(695)
#define BLDC_AXI_CONTROLLER_PWM_PERIOD_MAX          UINT32_C(12500)
#define BLDC_AXI_CONTROLLER_DEADTIME_MIN            UINT32_C(1)
#define BLDC_AXI_CONTROLLER_DEADTIME_MAX            UINT32_C(90)

#define BLDC_AXI_CONTROLLER_CONTROL_DRIVE_ENABLE    UINT32_C(1u << 0)
#define BLDC_AXI_CONTROLLER_CONTROL_AUTO_COMM       UINT32_C(1u << 1)
#define BLDC_AXI_CONTROLLER_CONTROL_DIRECTION       UINT32_C(1u << 2)
#define BLDC_AXI_CONTROLLER_CONTROL_SPEED_CTRL      UINT32_C(1u << 3)
#define BLDC_AXI_CONTROLLER_CONTROL_BRAKE_ENABLE    UINT32_C(1u << 4)

#define BLDC_AXI_CONTROLLER_PWM_CFG_DUTY_SHIFT      0u
#define BLDC_AXI_CONTROLLER_PWM_CFG_DUTY_MASK       UINT32_C(0x00000FFF)
#define BLDC_AXI_CONTROLLER_PWM_CFG_PERIOD_SHIFT    16u
#define BLDC_AXI_CONTROLLER_PWM_CFG_PERIOD_MASK     UINT32_C(0xFFFF0000)

#define BLDC_AXI_CONTROLLER_DEADTIME_HIGH_SHIFT     0u
#define BLDC_AXI_CONTROLLER_DEADTIME_HIGH_MASK      UINT32_C(0x000000FF)
#define BLDC_AXI_CONTROLLER_DEADTIME_LOW_SHIFT      8u
#define BLDC_AXI_CONTROLLER_DEADTIME_LOW_MASK       UINT32_C(0x0000FF00)

#define BLDC_AXI_CONTROLLER_COMM_CFG_STATE_SHIFT    0u
#define BLDC_AXI_CONTROLLER_COMM_CFG_STATE_MASK     UINT32_C(0x00000007)

/*
 * Hall/IRQ bit order follows the RTL:
 * bit 0 HA rise, bit 1 HA fall,
 * bit 2 HB rise, bit 3 HB fall,
 * bit 4 HC rise, bit 5 HC fall,
 * bit 6 FIFO not-empty.
 */
#define BLDC_AXI_CONTROLLER_IRQ_HA_RISE             UINT32_C(1u << 0)
#define BLDC_AXI_CONTROLLER_IRQ_HA_FALL             UINT32_C(1u << 1)
#define BLDC_AXI_CONTROLLER_IRQ_HB_RISE             UINT32_C(1u << 2)
#define BLDC_AXI_CONTROLLER_IRQ_HB_FALL             UINT32_C(1u << 3)
#define BLDC_AXI_CONTROLLER_IRQ_HC_RISE             UINT32_C(1u << 4)
#define BLDC_AXI_CONTROLLER_IRQ_HC_FALL             UINT32_C(1u << 5)
#define BLDC_AXI_CONTROLLER_IRQ_FIFO                UINT32_C(1u << 6)
#define BLDC_AXI_CONTROLLER_IRQ_HALL_MASK           UINT32_C(0x3F)

#define BLDC_AXI_CONTROLLER_FIFO_DATA_VALUE_MASK    UINT32_C(0x0000FFFF)

#define BLDC_AXI_CONTROLLER_FIFO_LEVEL_SHIFT        0u
#define BLDC_AXI_CONTROLLER_FIFO_LEVEL_MASK         UINT32_C(0x0000001F)
#define BLDC_AXI_CONTROLLER_FIFO_EMPTY              UINT32_C(1u << 8)
#define BLDC_AXI_CONTROLLER_FIFO_FULL               UINT32_C(1u << 9)

#define BLDC_AXI_CONTROLLER_SPEED_TARGET_COUNT_SHIFT 0u
#define BLDC_AXI_CONTROLLER_SPEED_TARGET_COUNT_MASK  UINT32_C(0x0000FFFF)
#define BLDC_AXI_CONTROLLER_SPEED_TARGET_STEP_SHIFT  16u
#define BLDC_AXI_CONTROLLER_SPEED_TARGET_STEP_MASK   UINT32_C(0x0FFF0000)

#define BLDC_AXI_CONTROLLER_SPEED_STATUS_DUTY_SHIFT  0u
#define BLDC_AXI_CONTROLLER_SPEED_STATUS_DUTY_MASK   UINT32_C(0x00000FFF)
#define BLDC_AXI_CONTROLLER_SPEED_STATUS_COUNT_SHIFT 12u
#define BLDC_AXI_CONTROLLER_SPEED_STATUS_COUNT_MASK  UINT32_C(0x0FFFF000)

#define BLDC_AXI_CONTROLLER_STATUS_HALL_SHIFT       0u
#define BLDC_AXI_CONTROLLER_STATUS_HALL_MASK        UINT32_C(0x00000007)
#define BLDC_AXI_CONTROLLER_STATUS_REQ_SHIFT        4u
#define BLDC_AXI_CONTROLLER_STATUS_REQ_MASK         UINT32_C(0x00000070)
#define BLDC_AXI_CONTROLLER_STATUS_ACTIVE_SHIFT     8u
#define BLDC_AXI_CONTROLLER_STATUS_ACTIVE_MASK      UINT32_C(0x00000700)
#define BLDC_AXI_CONTROLLER_STATUS_DEADTIME         UINT32_C(1u << 11)
#define BLDC_AXI_CONTROLLER_STATUS_PWM_HIGH         UINT32_C(1u << 12)
#define BLDC_AXI_CONTROLLER_STATUS_BRAKE_ACTIVE     UINT32_C(1u << 13)

#define BLDC_AXI_CONTROLLER_BRAKE_CFG_DUTY_SHIFT    0u
#define BLDC_AXI_CONTROLLER_BRAKE_CFG_DUTY_MASK     UINT32_C(0x00000FFF)

#endif
